---
- name: Configure Docker Machine
  hosts: docker
  become: yes
  tasks:
    - name: Install Required Packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG Key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    - name: Add Docker Repository
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run Redis Container
      docker_container:
        name: redis
        image: redis
        state: started
        restart_policy: always
        ports:
          - "6379:6379"

    - name: Verify Redis is Running
      command: docker ps
      register: docker_ps_output

    - name: Display Docker Output
      debug:
        msg: "{{ docker_ps_output.stdout }}"
