
services:
  web:
    build: .  # Build the Flask app from the Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"  # Map container's port 5000 to host's port 5000
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
    depends_on:
      - db  # Ensure the database starts before the web container

  db:
    image: postgres:15  # Use the official PostgreSQL 15 image
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persistent storage for database
    restart: always  # Restart container if it fails

volumes:
  pgdata:  # Named volume to persist PostgreSQL data
