name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
    types:
      - opened

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t my-private-registry/my-nginx-app:latest .

      - name: Push to Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login my-private-registry -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
          docker push my-private-registry/my-nginx-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull my-private-registry/my-nginx-app:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 80:80 my-private-registry/my-nginx-app:latest
